name: duvet
description: Duvet generates nice-looking coverage reports for your Dart projects.
version: 0.0.1
homepage: https://github.com/dstaley/duvet
author: Dylan Staley <staley.dylan@gmail.com>

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  args: ^1.5.1
  coverage: ^0.12.3
  hyper: ^1.0.1
  meta: ^1.1.6
  path: ^1.6.2
  sass: ^1.15.2
  shelf: ^0.7.4
  shelf_static: ^0.2.8

dev_dependencies:
  test: ^1.0.0
